name: Update site data (TSDB table + MUFC fixtures)

on:
  workflow_dispatch:
  schedule:
    - cron: "13 5 * * *"   # daily ~05:13 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build assets (table + fixtures + badges)
        env:
          TSDB_API_KEY: ${{ secrets.TSDB_API_KEY }}  # optional; falls back to '3'
        run: |
          python -u scripts/update_table.py
          python -u update_fixtures.py
          python -u scripts/update_badges.py
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt
          echo "assets/update_stamp.txt:"
          cat assets/update_stamp.txt

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.json assets/update_stamp.txt
          git commit -m "chore: refresh football data (table + fixtures + badges) $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "nothing to commit"
          git pull --rebase
          git push
