name: refresh football data

on:
  schedule:
    - cron: "*/60 * * * *"   # hourly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pandas

      - name: Build table.json
        run: python scripts/update_table.py

      - name: Build fixtures.json
        run: python scripts/update_fixtures.py

      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Commit & push assets
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/table.json assets/fixtures.json assets/update_stamp.txt || true
          git commit -m "chore: refresh football data $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "nothing to commit"
          git pull --rebase
          git push
