name: Update site data (table + fixtures + badges)

on:
  schedule:
    - cron: "0 6 * * *"      # daily 06:00 UTC
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Build the Premier League table (TheSportsDB) -> assets/table.json
      - name: Build table.json
        run: |
          python scripts/update_table.py

      # Build MUFC fixtures -> assets/fixtures.json
      - name: Build fixtures.json
        run: |
          python update_fixtures.py

      # Build club badges from current table using Wikipedia -> assets/badges.json
      - name: Build badges.json
        run: |
          python scripts/update_badges.py

      # Touch the update stamp (if you still like seeing it deployed)
      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/table.json assets/fixtures.json assets/badges.json assets/update_stamp.txt
          git commit -m "chore: refresh football data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
