name: Update site data (TSDB table + MUFC fixtures)

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Build football assets (table + fixtures + badges)
        run: |
          python scripts/update_table.py
          python scripts/update_fixtures.py
          python scripts/update_badges.py

      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/*.json assets/update_stamp.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh football data (table + fixtures) $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
