name: update-football-data

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write   # IMPORTANT: allow commit & push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build table.json (20 teams)
        run: python scripts/update_table.py

      - name: Build fixtures.json
        run: python scripts/update_fixtures.py

      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"
          git add assets/*.json assets/update_stamp.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh football data $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          fi
