name: build

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 mins
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---- TABLE stays as you already have it in your table workflow ----
      # If you have a separate workflow for table.json, leave it there.

      # ---- FIXTURES (Man United) ----
      - name: Build assets/fixtures.json
        run: python scripts/update_fixtures.py

      # ---- F1 ----
      - name: Build assets/f1.json
        run: python scripts/update_f1.py

      # ---- Touch update stamp (for top-right) ----
      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt
          cat assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/fixtures.json assets/f1.json assets/update_stamp.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh extras $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          else
            echo "No changes to commit."
          fi
