name: Update football data (table + MUFC fixtures)

on:
  schedule:
    - cron: "20,50 * * * *"   # every ~30 mins
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: football-data
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build table + badges
        run: python scripts/update_table.py

      - name: Build MUFC fixtures
        run: python scripts/update_fixtures.py

      - name: Touch update stamp
        run: |
          date -u +'%Y-%m-%dT%H:%M:%SZ' > assets/update_stamp.txt
          echo "Updated: $(cat assets/update_stamp.txt)"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Rebase first to avoid 'fetch first' errors
          git pull --rebase origin main || true
          git add assets/table.json assets/badges.json assets/fixtures.json assets/update_stamp.txt
          git commit -m "chore: refresh football data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push origin HEAD:main
