name: refresh extras

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Build weather.json
        run: python scripts/update_weather.py

      - name: Build steam specials
        run: python scripts/update_extras.py

      - name: Build F1 results
        run: python scripts/update_f1.py

      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/weather.json assets/steam_specials.json assets/f1.json assets/update_stamp.txt || true
          git commit -m "chore: refresh extras $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "nothing to commit"
          git pull --rebase
          git push
