name: Update football data / build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  workflow_call: {}   # allows reuse later, but this file still runs by itself

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TSDB_KEY: ${{ secrets.TSDB_KEY }}   # ok if undefined; scripts fall back to '3'
      TSDB_LEAGUE_ID: "4328"
      SEASON: "2025-2026"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Update EPL table (20 rows guard)
        run: python3 scripts/update_table.py

      - name: Update badges (crest URLs)
        run: python3 scripts/update_badges.py

      - name: Update fixtures (MUFC)
        run: python3 scripts/update_fixtures.py

      - name: Touch update stamp (force Pages redeploy)
        run: date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Verify outputs
        run: |
          echo "== assets =="
          ls -lah assets || true
          echo "== table.json (first 400 bytes) =="
          head -c 400 assets/table.json || true; echo
          echo "== badges.json (first 400 bytes) =="
          head -c 400 assets/badges.json || true; echo
          echo "== fixtures.json (first 400 bytes) =="
          head -c 400 assets/fixtures.json || true; echo

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "data: refresh table, badges, fixtures"
            git pull --rebase origin main || true
            git push
          fi
