name: Update extras data / build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (example)
  workflow_call: {}          # <-- enables reuse

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate extras (weather/free games)
        run: |
          # your existing steps here that write:
          # assets/weather.json, assets/free_games.json
          echo "extras pipeline here"

      - name: Touch update stamp (force Pages redeploy)
        run: date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "data: refresh extras"
            git pull --rebase origin main || true
            git push
          fi
