name: update-extras
on:
  schedule: [{ cron: "0 */3 * * *" }]  # every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install requests

      - name: Weather
        run: python scripts/update_weather.py

      - name: Steam specials
        run: python scripts/update_extras.py

      - name: F1 (best-effort)
        run: python scripts/update_f1.py || true

      - name: Touch update stamp (same file used by both pages)
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt
          cat assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add assets/*.json assets/update_stamp.txt
          git commit -m "chore: refresh extras $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "no changes"
          git pull --rebase
          git push
