name: Update football data (table + fixtures + badges)

on:
  schedule:
    - cron: "0 6 * * *"    # daily 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build table.json + badges.json
        run: python scripts/update_table.py

      - name: Build fixtures.json
        run: python scripts/update_fixtures.py

      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt
          cat assets/update_stamp.txt

      - name: Commit & push assets
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/table.json assets/badges.json assets/fixtures.json assets/update_stamp.txt
          git commit -m "chore: refresh football data $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes"
          git pull --rebase origin $(git rev-parse --abbrev-ref HEAD) || true
          git push || true
