name: update-football-data
on:
  schedule: [{ cron: "*/60 * * * *" }]  # hourly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: pip install requests beautifulsoup4 python-dateutil pytz

      - name: Build table.json (20 teams)
        run: python scripts/update_table.py

      - name: Build fixtures.json
        run: python scripts/update_fixtures.py

      - name: Touch update stamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > assets/update_stamp.txt
          cat assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add assets/table.json assets/fixtures.json assets/update_stamp.txt
          git commit -m "chore: refresh football data $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "no changes"
          git pull --rebase
          git push
