name: Update extras data (weather + free games)

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */12 * * *' # twice a day; adjust as needed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (if any)
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt || true

      - name: Build extras assets (weather + free Steam games)
        run: |
          set -e
          mkdir -p assets
          # Use your working scripts or inline requests; keep whatever worked last time:
          # Example assumes you have scripts/fetch_helpers.py etc.
          python scripts/fetch_helpers.py extras  # (or your own calls)
          # Ensure the two files exist (fallback placeholders if scripts no-op)
          [ -f assets/weather.json ] || echo '{"city":"Leeds","now":null,"forecast":[]}' > assets/weather.json
          [ -f assets/free_games.json ] || echo '[]' > assets/free_games.json

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh extras (weather + free games)"
          file_pattern: |
            assets/weather.json
            assets/free_games.json
