name: update-extras

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # your existing scripts (weather, steam, f1) – keep them as-is
      - name: Weather
        run: python scripts/update_weather.py

      - name: Steam specials
        run: python scripts/update_extras.py

      - name: F1 (best-effort)
        run: python scripts/update_f1.py || true

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"
          git add assets/*.json || true
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: refresh extras $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            git push
          fi
