name: Update site data (table + fixtures)

on:
  schedule:
    - cron: "0 6 * * *"      # daily 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # (Optional) quick visibility for path issues in logs
      - name: Show repo tree (debug)
        run: ls -la && echo && find . -maxdepth 2 -print

      # MUST exist: scripts/update_table.py -> writes assets/table.json + assets/badges.json
      - name: Build table.json + badges.json
        run: python scripts/update_table.py

      # MUST exist: scripts/update_fixtures.py -> writes assets/fixtures.json
      - name: Build fixtures.json
        run: python scripts/update_fixtures.py

      - name: Touch update stamp
        run: date -u +'%Y-%m-%dT%H:%M:%SZ' > assets/update_stamp.txt

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/table.json assets/badges.json assets/fixtures.json assets/update_stamp.txt
          git commit -m "chore: refresh football data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          # avoid non-fast-forward errors if multiple runs overlap
          git pull --rebase || true
          git push
